import { describe, it, expect, beforeEach } from "vitest";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { writeFile } from "node:fs/promises";
import { CaseStore } from "../../src/storage/caseStore.js";
import { HypothesisStore } from "../../src/analysis/hypothesisStore.js";
import { hypothesisAutoKey } from "../../src/analysis/hypothesis.js";

describe("HypothesisStore", () => {
  let store: HypothesisStore;
  let cases: CaseStore;
  beforeEach(async () => {
    const root = await mkdtemp(join(tmpdir(), "dfir-hypo-"));
    cases = new CaseStore(root);
    await cases.createCase({ caseId: "c1", name: "n", investigator: "i", aiProvider: null });
    store = new HypothesisStore(cases);
  });

  it("returns [] when no hypotheses exist", async () => {
    expect(await store.load("c1")).toEqual([]);
  });

  it("adds an analyst hypothesis (server-assigned id + timestamps, born touched)", async () => {
    const h = await store.add("c1", { title: "Initial access was phishing", author: "Alice", relatedEventIds: ["e1"] });
    expect(h.id).toBeTruthy();
    expect(h.createdAt).toBeTruthy();
    expect(h.source).toBe("analyst");
    expect(h.analystTouched).toBe(true);
    expect(h.author).toBe("Alice");
    const list = await store.load("c1");
    expect(list).toHaveLength(1);
    expect(list[0]).toMatchObject({ title: "Initial access was phishing", relatedEventIds: ["e1"] });
  });

  it("throws on an empty title", async () => {
    await expect(store.add("c1", { title: "   " })).rejects.toThrow(/title/);
  });

  it("updates status/notes and marks analystTouched; returns null for an unknown id", async () => {
    const h = await store.add("c1", { title: "Staging before encryption" });
    const updated = await store.update("c1", h.id, { status: "supported", notes: "confirmed via prefetch" });
    expect(updated?.status).toBe("supported");
    expect(updated?.notes).toBe("confirmed via prefetch");
    expect(await store.update("c1", "nope", { status: "refuted" })).toBeNull();
  });

  it("removes a hypothesis by id", async () => {
    const h = await store.add("c1", { title: "Lateral movement via SMB" });
    expect(await store.remove("c1", h.id)).toBe(true);
    expect(await store.remove("c1", h.id)).toBe(false);
    expect(await store.load("c1")).toEqual([]);
  });

  it("applyAutoGenerated merges synthesis seeds, refreshes pristine, persists only on change", async () => {
    const seeds = [{ sourceKey: hypothesisAutoKey("Phishing"), title: "Phishing", description: "v1", expectedOutcome: "", status: "open" as const, relatedTechniques: [], relatedEventIds: [], relatedIocIds: [] }];
    const first = await store.applyAutoGenerated("c1", seeds, "2026-06-22T00:00:00.000Z");
    expect(first.changed).toBe(true);
    expect((await store.load("c1"))[0].source).toBe("synthesis");

    // Same seeds again → no change.
    const again = await store.applyAutoGenerated("c1", seeds, "2026-06-22T02:00:00.000Z");
    expect(again.changed).toBe(false);

    // Reworded seed → refresh the pristine hypothesis.
    const reworded = [{ ...seeds[0], description: "v2" }];
    const third = await store.applyAutoGenerated("c1", reworded, "2026-06-22T03:00:00.000Z");
    expect(third.changed).toBe(true);
    expect((await store.load("c1"))[0].description).toBe("v2");
  });

  it("applyAutoGenerated does not clobber an analyst-touched synthesis hypothesis", async () => {
    const seeds = [{ sourceKey: hypothesisAutoKey("Phishing"), title: "Phishing", description: "v1", expectedOutcome: "", status: "open" as const, relatedTechniques: [], relatedEventIds: [], relatedIocIds: [] }];
    await store.applyAutoGenerated("c1", seeds, "2026-06-22T00:00:00.000Z");
    const stored = (await store.load("c1"))[0];
    await store.update("c1", stored.id, { status: "supported" });
    await store.applyAutoGenerated("c1", [{ ...seeds[0], description: "v2", status: "refuted" as const }], "2026-06-22T04:00:00.000Z");
    const after = (await store.load("c1"))[0];
    expect(after.status).toBe("supported");
    expect(after.description).toBe("v1");
  });

  it("backfills statusHistory (issue #95) for a hypotheses.json written before that field existed", async () => {
    const legacy = [{
      id: "hp1", title: "Old-format hypothesis", description: "", expectedOutcome: "",
      status: "refuted", relatedTechniques: [], relatedEventIds: [], relatedIocIds: [],
      assignee: "", notes: "", source: "analyst", analystTouched: true,
      createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-02T00:00:00.000Z",
    }];
    await writeFile(join(cases.stateDir("c1"), "hypotheses.json"), JSON.stringify(legacy));
    const [h] = await store.load("c1");
    expect(h.statusHistory).toEqual([{ status: "refuted", changedAt: "2026-01-01T00:00:00.000Z" }]);
  });
});
