import type { InvestigationState } from "../stateTypes.js";
import { falsePositiveEventIds, type FalsePositiveMarker } from "../falsePositive.js";
import { sanitizeHypotheses } from "../hypothesis.js";
import { collectedEvidenceClasses, gateRefutedSeeds } from "../refutationGate.js";
import type { stripAiExtractedFrom } from "../responseSchema.js";
import type { SynthesisContext } from "./synthesis.js";

// The hypothesis step of synthesis post-processing. Lifted out of synthesis.ts, which sits at the
// file-size limit (#933 item 22).

/**
 * Auto-generate hypotheses (issue #140). Merge the model's hypotheses into the per-case store,
 * refreshing pristine auto ones and FREEZING any the analyst touched (see mergeHypotheses). Only
 * when the model actually returned some — an omitted field must never prune the analyst's set.
 *
 * Sanitized against the FINAL event/IOC ids so evidence links can't dangle. A side store, not part
 * of InvestigationState, and it runs after the state is persisted so a failure here cannot lose the
 * synthesis.
 *
 * The refutation gate runs last, on the sanitized seeds. The model is allowed to say "refuted", but
 * only when the collection could have seen the thing it is denying — a refutation resting on an
 * evidence class nobody collected is a fact about the collection, not about the host, so it is
 * downgraded to `unknown` with the missing class named. Like every other deterministic pass here it
 * can only ever WEAKEN a claim. See refutationGate.ts.
 */
export async function autoGenerateHypotheses(
  ctx: SynthesisContext,
  caseId: string,
  hypotheses: ReturnType<typeof stripAiExtractedFrom>["hypotheses"],
  next: InvestigationState,
  markers: FalsePositiveMarker[],
): Promise<void> {
  if (!ctx.opts.hypothesisStore || !hypotheses || !hypotheses.length) return;
  const validEventIds = new Set(next.forensicTimeline.map((e) => e.id));
  const validIocIds = new Set(next.iocs.map((i) => i.id));
  const sanitized = sanitizeHypotheses(hypotheses, validEventIds, validIocIds);
  const { seeds } = gateRefutedSeeds(sanitized, collectedEvidenceClasses(next.forensicTimeline));
  const elig = { eligibleEventIds: validEventIds, falsePositiveEventIds: falsePositiveEventIds(markers) };
  await ctx.opts.hypothesisStore.applyAutoGenerated(caseId, seeds, new Date().toISOString(), elig);
}
