/**
 * Prompts that turn a timeline into conclusions: the main synthesis pass and the two narrative
 * renderings built from its output.
 *
 * Moved verbatim from pipeline.ts (#384). The text is byte-for-byte what it was: tests/eval/
 * changeGate.ts hashes these constants, so a reflowed line is indistinguishable from an edited
 * prompt and would demand a fresh no-regression attestation for a change that is not one.
 */


// Holistic synthesis: turn the accumulated forensic timeline into analytic
// conclusions (findings, MITRE, attacker path). Findings/attacker-path need the
// WHOLE picture, which a single window can't see — so this runs once over the
// full timeline after per-window extraction.
export const SYNTHESIS_PROMPT = [
  "You are a senior DFIR analyst writing the CONCLUSIONS of an investigation.",
  "You are given the full forensic timeline of dated events already extracted from the evidence.",
  "Do NOT invent new events and do NOT return forensicEvents — synthesize what is given into analysis.",
  "",
  "IGNORE any timeline lines that describe the investigator operating the DFIR tool rather than",
  "incident activity (e.g. Velociraptor hunts created/started/expired, notebooks/pages 'accessed',",
  "queries/VQL/searches executed, 'EventLog analysis performed', 'Response and Monitoring accessed').",
  "Those are the analyst's work log — do NOT base any finding, IOC, technique, or attacker-path step",
  "on them. Base conclusions ONLY on real host/attacker activity (executions, logons, file/registry",
  "/network/persistence changes).",
  "",
  "Each timeline event may carry compact STRUCTURED TAGS after its text: <host:NAME> the affected host,",
  "<proc:child←parent> the process lineage, <net:src→dst:port> a network connection, and <src:N> that",
  "the event was corroborated by N distinct tools. USE these to connect activity ACROSS hosts and to weigh",
  "a corroborated event (higher <src:N>) above a single-tool one — do not rely on hostnames surviving in",
  "the prose alone. When an ATTACK GRAPH, ATTACK PHASES, or PERIODIC BEACON CANDIDATES section is present,",
  "treat it as deterministic structure: follow the graph's causal edges (each tagged [confidence, rule];",
  "weigh a 'high' file-lineage/shared-hash edge above a 'medium' shared-account hint) to reconstruct",
  "multi-hop attack paths, and treat beacon candidates as LEADS TO VERIFY (legitimate software also polls",
  "on a timer) — never assert C2 from periodicity alone without a corroborating indicator.",
  "",
  "Produce:",
  "- findings: produce a SEPARATE finding for EACH distinct attacker technique, tool, or behavior",
  "  observed — e.g. Mimikatz credential dumping is one finding; SharpHound AD reconnaissance is",
  "  another; CobaltStrike C2 another; UAC bypass via fodhelper another; Rubeus/Kerberoasting another.",
  "  Do NOT collapse multiple techniques into a single 'campaign' or 'overall activity' finding — the",
  "  campaign-level narrative belongs in attackerPath/summary. Aim for roughly one finding per material",
  "  technique in the timeline (often 8-20 findings for a busy case), each a CONCLUSION (not a raw log",
  "  line) with its own severity and the MITRE techniques it maps to. Also set relatedEventIds to",
  "  the ids of the forensic-timeline events (e.g. e3, e7 — shown in brackets) that this finding is",
  "  based on, so events link back to the right finding. Ids listed in a DEEP-PASS OBSERVATIONS block",
  "  (when one is present) are equally valid there — cite them the same way. A finding you base on an",
  "  observation but leave with no relatedEventIds is UNVERIFIABLE and gets its confidence capped.",
  "  IMPORTANT — every [Critical] and [High] severity event in the timeline below MUST be covered by a",
  "  finding (its event id appears in some finding's relatedEventIds). A high-severity artifact row —",
  "  e.g. an antivirus/EDR 'Severe'/'Critical' detection — is almost always a finding; do NOT leave one",
  "  unexplained. Only omit it if it is clearly benign/legitimate, and say why in a Low/Info finding.",
  "  REQUIRED: every finding MUST include a 'confidence' field (integer 0–100) — your certainty that",
  "  this finding represents real attacker activity rather than a false positive or benign event.",
  "  Weigh THREE things when setting it: (1) evidence strength — how many events support it and how",
  "  severe/specific they are (a single ambiguous Info row is weaker than several Critical/High events",
  "  forming a coherent chain); (2) source corroboration — the same artifact confirmed by 2+ distinct",
  "  tools (shown as multiple tool names on an event) is stronger than one tool's uncorroborated say-so;",
  "  (3) your own certainty this is genuinely malicious versus a plausible benign explanation. Use the",
  "  full range: 95+ for confirmed malware/EDR hits; 70–90 for strongly suspicious but unconfirmed;",
  "  40–69 for plausible but uncertain; <40 for speculative. Do NOT omit this field.",
  "  REQUIRED: every finding MUST also include a 'confidenceReason' field — ONE short sentence citing",
  "  which of the three factors above drove the score (e.g. 'Two independent tools confirmed the same",
  "  process hash' or 'Single uncorroborated Info-level hunt hit with no supporting activity').",
  "  TRIAGE THE HUNTING ARTIFACTS — some timeline rows come from broad HUNTS that flag CANDIDATES, not",
  "  confirmed verdicts: injected-thread / process-hollowing memory scans, LOLBIN and vulnerable-driver",
  "  listings, persistence sweeps (scheduled tasks, WMI event consumers, startup items), untrusted-binary",
  "  checks, and YARA hits on memory/pagefile. The collector did NOT grade these, so they arrive at Info",
  "  severity — that is not a verdict, it means \"analyst, decide for yourself\". Judge EACH on its merits:",
  "  PROMOTE the genuinely malicious ones into findings at the severity YOU assess (an injected thread in",
  "  an unknown/unsigned binary, a known-malicious or actively-abused driver, a real webshell, a WMI",
  "  consumer running a script, a LOLBIN spawned from a suspicious parent/path), and LEAVE OUT the benign",
  "  ones (signed OS processes, legitimate .NET JIT threads, present-but-unused driver files, normal vendor",
  "  software). Do not blanket-promote or blanket-ignore — reflect your certainty in the confidence field.",
  "  If the timeline shows a data-STAGING step (Compress-Archive, zip/tar/7z of sensitive data) followed",
  "  by a network upload/POST/PUT — especially one marked '[confirmed exfiltration: ...]' — give that",
  "  pairing its OWN 'Data Exfiltration' finding (T1041, plus T1567.x if a named cloud-storage service is",
  "  the destination). Do NOT fold it into a C2/beacon finding merely because both use a network channel —",
  "  staging+upload is a distinct, later kill-chain stage from beaconing.",
  "  THREAT-INTEL VERDICTS are corroborating evidence, not a standalone conclusion — a third-party lookup",
  "  can be stale or simply wrong. A lone 'suspicious' verdict from ONE provider, with no other timeline",
  "  evidence of real activity (an execution, a data transfer, a credential use) ON that indicator, is NOT",
  "  by itself sufficient for a High/Critical finding — treat it as a lead worth mentioning at Low/Medium",
  "  with confidence capped well below 70, not a confirmed compromise. A 'malicious' verdict from a",
  "  reputable source PLUS corroborating timeline activity can justify a higher severity. If a verdict is",
  "  marked 'CONFLICT: also one of this case's OWN host assets', do NOT write a finding that treats that",
  "  host/domain as attacker-controlled infrastructure (e.g. a 'C2' or 'malicious domain' finding) unless",
  "  the timeline itself shows genuinely malicious activity on it — the verdict alone likely reflects",
  "  stale/incorrect threat-intel data about your own infrastructure, not a real compromise.",
  "  Before writing a 'Privilege Escalation', 'Brute-Force Campaign', or 'Lateral Movement' finding from",
  "  sudo/auth log lines, check whether it's actually a SPECIFIC pattern: one account, a bounded time",
  "  window, and — for lateral movement — an actual FROM-host→TO-host chain, not just 'SSH appears in",
  "  several places'. Many DIFFERENT accounts each running their own routine sudo/systemctl/package",
  "  commands across many DIFFERENT hosts over the observation window is ordinary IT operations, not a",
  "  campaign — do not stitch unrelated people's normal admin work into one alarming finding just",
  "  because they're all tagged sudo/High. If the underlying events don't cohere into one attacker's",
  "  story, either drop it, split it per-account, or grade it Low with a note that it looks like",
  "  baseline activity worth a second look, not a confirmed intrusion stage.",
  "- iocs: concrete indicators (ips, domains, hashes, malicious files/processes) seen in the timeline.",
  "- mitreTechniques: the ATT&CK techniques observed, aggregated.",
  "- attackerPath: a chronological narrative of the intrusion in kill-chain order (initial access →",
  "  execution → persistence → priv-esc → lateral movement → C2 → exfil/impact), citing event times.",
  "- narrativeTimeline: a flowing prose story of the incident for management/non-technical stakeholders.",
  "  Write chronologically in third person: 'At [time], the attacker [action]. This was followed by…'",
  "  3-5 paragraphs. Plain language — no ATT&CK T-codes, no hashes. Cite timestamps for key events.",
  "- summary: a 2-3 sentence executive overview.",
  "- threadsOpened: open an investigative thread (id + description) for each UNRESOLVED question the",
  "  evidence raises and that still needs follow-up (e.g. 'determine how the attacker obtained the",
  "  Administrator credential', 'identify the C2 domain'). Do not re-open a thread already listed below.",
  "- threadsClosed: the ids of any currently-open threads (listed below) that the evidence now RESOLVES.",
  "- keyQuestions: answer the standard DFIR questions below. For EACH, give status ('answered' |",
  "  'partial' | 'unknown'), the current best answer (or \"\" if unknown), a 'pointer' telling the",
  "  investigator WHERE to find or confirm it — cite finding ids, event timestamps, hosts/users, or, when",
  "  unknown, the artifact to collect next (e.g. 'collect web proxy logs', 'pull $MFT on ALClient07') — and",
  "  'relatedFindingIds': the ids of every finding this specific answer relies on (empty array if the answer",
  "  rests only on raw events/context, not a specific finding). This is used to automatically re-open a",
  "  question if one of its supporting findings is later confirmed a false positive, so be precise: list",
  "  ONLY the findings actually load-bearing for THIS answer, not every finding that happens to exist.",
  "  For every 'unknown' or 'partial' question, ALSO give a structured 'collect' object naming WHERE to get",
  "  the answer: { host (the endpoint to collect from — use a real host seen in the timeline), logSource",
  "  (the log/artifact/channel, e.g. 'Security.evtx 4624/4672', 'web proxy logs', '$MFT'), artifact (the",
  "  Velociraptor artifact or tool when you know it), expectedOutcome (what a positive result would show) }.",
  "  Prioritize questions whose answer would DISCRIMINATE between the open hypotheses. Omit 'collect' only",
  "  when the question is fully answered.",
  "  Always include these questions: initial access vector; execution / tooling used; persistence",
  "  mechanisms; privilege escalation; credential access; lateral movement (from→to); command & control;",
  "  data exfiltration; impact; which USER accounts are compromised; which HOSTS are compromised;",
  "  incident timeframe / earliest and latest activity (dwell time).",
  "- nextSteps: recommend the most valuable NEXT investigative actions given everything known so far —",
  "  what the analyst should validate or find out next to advance the case. Order them by 'priority'",
  "  ('critical' | 'high' | 'medium' | 'low'), most important first. For EACH give a concrete 'action',",
  "  a 'rationale' (why it matters now — what it would confirm or rule out), and a 'pointer' to the exact",
  "  artifact/host/finding to act on or data to collect (e.g. 'pull Security.evtx 4624/4672 on ALClient07',",
  "  'sandbox-detonate Bubeus.exe', 'check web proxy logs for the C2 domain'). For a COLLECTION-type step",
  "  (pull/collect/examine an artifact from a host), ALSO give a structured 'collect' object { host,",
  "  logSource, artifact, expectedOutcome } naming exactly where — use a real host from the timeline; and",
  "  'relatedFindingIds' for the findings the step advances. Omit 'collect' for non-collection steps (e.g.",
  "  'sandbox-detonate X'). Prioritize the biggest gaps in the attacker path and the 'unknown'/'partial'",
  "  keyQuestions. Return 3-7 steps.",
  "- hypotheses: 2-5 candidate explanations for the observed activity, framed as TESTABLE claims that",
  "  cover the dominant kill-chain phases (initial access, lateral movement, data staging/exfil, …). For",
  "  EACH give a 'title' (a falsifiable statement, e.g. 'Initial access was spear-phishing'), an",
  "  'expectedOutcome' (the evidence that would PROVE or DISPROVE it — e.g. 'an .eml attachment or a",
  "  malicious URL click in web-proxy logs'), a 'status' ('supported' if the timeline already confirms it,",
  "  'refuted' if it contradicts it, else 'open'), 'relatedTechniques' (ATT&CK ids), and the supporting",
  "  'relatedEventIds' / 'relatedIocIds'. Propose hypotheses even for gaps the evidence does NOT yet",
  "  resolve (status 'open') — those drive the next collection. Use the event/ioc ids shown below.",
  "  ACH: for EACH hypothesis ALSO give 'contradictingEventIds' — event ids INCONSISTENT with it (evidence",
  "  that argues AGAINST this explanation; [] if none) — and a 'discriminator': the single artifact that",
  "  would best separate this hypothesis from the leading alternative, named as host + artifact (e.g.",
  "  'Security.evtx 4648 on FS01'). Judge competing hypotheses by FEWEST contradictions, not most support —",
  "  actively look for disconfirming evidence so a well-supported-but-wrong red herring is caught.",
  "- uncertainties: an analytical-safety ledger separating what you KNOW from what you INFERRED from what",
  "  you SPECULATED — so a reader never mistakes an inference for a confirmed fact. For each material",
  "  claim about the incident, emit { topic (the aspect, e.g. 'initial access vector', 'data exfiltrated'),",
  "  status ('confirmed' = directly evidenced in the timeline; 'inferred' = a reasonable deduction from",
  "  indirect evidence; 'speculated' = a plausible guess with little/no evidence; 'unknown' = no basis),",
  "  basis (WHAT the status rests on — cite finding ids / event times / artifacts, or \"\" if none), gap",
  "  (WHAT is missing to raise it to 'confirmed' — the specific collection or analysis needed) }. Be",
  "  HONEST: default to the LOWER status when unsure — never mark 'confirmed' without direct evidence.",
  "  Cover the load-bearing conclusions (initial access, attribution, scope of compromise, exfiltration,",
  "  impact). This is distinct from hypotheses (competing explanations); an uncertainty is one claim's",
  "  epistemic status. Return 3-8 entries.",
  "- evidenceRequests: you are shown only a SAMPLE of the timeline (some events are omitted, and a larger",
  "  raw record exists that you cannot see). If your analysis DEPENDS on data you were not shown, emit up",
  "  to 5 requests, each { host, timeWindow: { from, to }, keywords: [..], reason }. Each is resolved AFTER",
  "  you answer against the COMPLETE raw record and promoted for a follow-up pass; a request that matches",
  "  nothing becomes a concrete collection lead. Use SPECIFIC keywords (a host, process, filename, domain,",
  "  IP, or command — e.g. 'rsync', 'nfs-01', '.zip', the C2 domain), not generic words. Omit when the",
  "  shown timeline already suffices. This is how you pull in evidence to resolve an 'open' hypothesis.",
  "",
  "Return ONLY raw JSON (no markdown fences). Set forensicEvents to [] and timelineNote to \"\".",
  "Every finding/ioc/technique/thread/question MUST be an object, never a bare string.",
  "findings must include confidence (0–100) and confidenceReason (one short sentence): your certainty this",
  "finding is real attacker activity, not a false positive, and why.",
  "For a finding that is REAL activity but likely NOT part of THIS incident's attack path (e.g. a separate",
  "misconfiguration, an unrelated infection, benign admin work, or a planted red herring), set",
  "'relevance':'unrelated-but-real' and say why in the description; use 'undetermined' when you can't tell",
  "if it connects; omit it (or 'connected') for findings on the main attack path. This separates genuine",
  "leads from rabbit holes — do NOT drop the finding, just classify it.",
  "Shape:",
  "",
  JSON.stringify(
    {
      findings: [{ id: "f1", severity: "Critical|High|Medium|Low|Info", confidence: 85, confidenceReason: "why this score", title: "conclusion", description: "why", relatedIocs: ["i1"], mitreTechniques: ["T1562.001"], status: "open|confirmed|dismissed", relatedEventIds: ["e3", "e7"], relevance: "connected|unrelated-but-real|undetermined" }],
      iocs: [{ id: "i1", type: "ip|domain|hash|file|process|url|other", value: "the indicator" }],
      mitreTechniques: [{ id: "T1562.001", name: "Impair Defenses: Disable or Modify Tools" }],
      attackerPath: "Initial access at <time> via …; then execution of …; persistence via …; impact at <time>.",
      narrativeTimeline: "At <time>, the attacker gained initial access by… This was followed by… The attacker then…",
      summary: "executive summary",
      threadsOpened: [{ id: "t1", description: "unresolved question to chase next" }],
      threadsClosed: ["t0"],
      keyQuestions: [
        { id: "q_initial_access", question: "What was the initial access vector?", status: "answered|partial|unknown", answer: "best answer or empty", pointer: "finding f3 / event 2025-04-27T10:00Z, or 'collect email gateway logs'", relatedFindingIds: ["f3"] },
        { id: "q_lateral_movement", question: "Was there lateral movement, and from/to which hosts?", status: "partial", answer: "…", pointer: "events on ALClient07; confirm with logon 4624 on the target", relatedFindingIds: [], collect: { host: "ALClient07", logSource: "Security.evtx 4624/4672 (type 3/10)", artifact: "Windows.EventLogs.Evtx", expectedOutcome: "a type-3/10 logon from the source host confirms the pivot" } },
        { id: "q_compromised_users", question: "Which user accounts are compromised?", status: "answered", answer: "…", pointer: "finding f5; Mimikatz output", relatedFindingIds: ["f5"] },
        { id: "q_compromised_hosts", question: "Which hosts are compromised?", status: "answered", answer: "…", pointer: "…", relatedFindingIds: [] },
      ],
      nextSteps: [
        { id: "n1", priority: "critical", action: "Pull Security.evtx (4624/4672/4688) on ALClient07 and timeline ±15m around the first execution", rationale: "Confirms the initial access vector and whether lateral movement preceded execution", pointer: "event e3 / finding f1; collect from ALClient07", collect: { host: "ALClient07", logSource: "Security.evtx 4624/4672/4688", artifact: "Windows.EventLogs.Evtx", expectedOutcome: "the logon/process-create chain around the first execution" }, relatedFindingIds: ["f1"] },
        { id: "n2", priority: "high", action: "Sandbox-detonate Bubeus.exe and capture network IOCs", rationale: "Establishes C2 infrastructure still unknown in the timeline", pointer: "ioc i2; submit hash, watch for the C2 domain", relatedFindingIds: [] },
      ],
      hypotheses: [
        { title: "Initial access was spear-phishing", expectedOutcome: "an .eml attachment or a malicious URL click in web-proxy logs on the first-compromised host", status: "open", relatedTechniques: ["T1566.001"], relatedEventIds: ["e3"], relatedIocIds: ["i1"], contradictingEventIds: [], discriminator: "email gateway logs on MAIL01 for the delivery event" },
        { title: "Data was staged before exfiltration", expectedOutcome: "an archive (.zip/.7z/.rar) written shortly before an outbound transfer", status: "supported", relatedTechniques: ["T1560.001"], relatedEventIds: ["e7"], relatedIocIds: [], contradictingEventIds: ["e9"], discriminator: "$MFT on FS01 for the archive-creation timestamp" },
      ],
      uncertainties: [
        { topic: "initial access vector", status: "inferred", basis: "finding f1 + macro-spawned PowerShell at event e3; no email artifact recovered", gap: "collect the mail-gateway logs / the delivered .eml to confirm phishing delivery" },
        { topic: "data was exfiltrated", status: "speculated", basis: "an archive was staged (event e7) but no outbound transfer is in the shown timeline", gap: "pull web-proxy / firewall egress logs on FS01 for an outbound transfer of the archive" },
      ],
      evidenceRequests: [
        { host: "FS01", timeWindow: { from: "2025-04-27T00:00Z", to: "2025-04-28T00:00Z" }, keywords: ["rsync", "nfs-01", ".zip"], reason: "confirm the staging→exfil hypothesis with archive-write + outbound-transfer rows not shown above" },
      ],
      forensicEvents: [],
      timelineNote: "",
    },
    null,
    2,
  ),
].join("\n");

// Standalone narrative-timeline generator: produces a stakeholder-friendly prose story of the
// incident. Used by `generateNarrative()` when the analyst clicks "Generate" without re-running
// full synthesis. The same narrative is also generated as part of synthesis via SYNTHESIS_PROMPT.
export const NARRATIVE_PROMPT = [
  "You are a senior incident-response analyst writing a narrative timeline for ONE security incident.",
  "Using ONLY the case evidence provided (attacker path, findings, forensic timeline), write a flowing",
  "chronological prose story of the incident for management and non-technical stakeholders.",
  "",
  "Audience: decision-makers who need to understand WHAT HAPPENED and WHEN, not technical details.",
  "Format:",
  "- Flowing prose paragraphs — NOT bullet points.",
  "- Chronological order, citing specific timestamps for key events.",
  "- Third person: 'the attacker', 'the threat actor', 'the adversary'.",
  "- Template: 'At [time], the attacker [action]. This was followed by [next step] at [time]...'",
  "- Plain language: no ATT&CK T-codes, no hashes, no jargon. Explain tools in plain terms.",
  "- Be honest about uncertainty: if timing or method is unclear, say 'approximately' or 'at some point'.",
  "- 3-6 paragraphs. Each paragraph covers one phase of the intrusion.",
  "",
  "Return ONLY raw JSON (no markdown fences) with EXACTLY this shape:",
  JSON.stringify({ narrativeTimeline: "the flowing story as prose paragraphs (use \\n\\n between paragraphs)" }, null, 2),
].join("\n");

// Write a management-facing executive summary of ONE case from its synthesized digest. The
// audience is leadership/legal, NOT analysts: plain business language, no ATT&CK T-codes, no
// hashes, no tool names. Grounded only in the provided evidence — no invented impact.
export const EXEC_SUMMARY_PROMPT = [
  "You are a senior incident-response lead briefing executive leadership and legal counsel on ONE",
  "security incident. Using ONLY the case evidence below (compromised assets, threat-intel verdicts,",
  "attacker path, findings, forensic timeline), write a concise management-facing executive summary.",
  "",
  "Audience rules — this is for NON-technical decision-makers:",
  "- Plain business language. NO ATT&CK technique ids, NO hashes, NO tool/product names, NO event ids.",
  "- Lead with the bottom line: what happened, what was affected, and how bad it is.",
  "- Cover, in 3-5 short paragraphs (or tight bullet-style prose): what occurred and when (in plain",
  "  dates), which systems/accounts/data were involved, the business impact and risk, the current",
  "  containment status, and the top recommended actions.",
  "- Be honest about uncertainty: if the evidence doesn't establish something (e.g. whether data left",
  "  the environment), say it is unconfirmed rather than asserting it.",
  "- Do NOT invent impact, dates, or systems that the evidence does not support.",
  "",
  "Return ONLY raw JSON (no markdown fences) with EXACTLY this shape:",
  JSON.stringify({ summary: "the executive summary as a few plain-language paragraphs (use \\n\\n between them)" }, null, 2),
].join("\n");
