import {
  mkdir,
  mkdtemp,
  open,
  readdir,
  readFile,
  rename as renamePath,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { join, dirname, isAbsolute } from "node:path";
import { randomUUID } from "node:crypto";
import { isValidCaseId, type CaseStore } from "../storage/caseStore.js";
import type { CaseMeta } from "../types.js";
import { destinationKey } from "../storage/portableFilename.js";
import {
  CASE_ZIP_MAX_CONTROL_BYTES,
  CASE_ZIP_MAX_TOTAL_BYTES,
  extractCaseZipEntry,
  readCaseZipEntry,
  writeAll,
  type CaseZipEntry,
} from "./caseZipReader.js";

/**
 * Restore an opened case ZIP into a NEW case (#1828). Shared by the `.dfircase` import
 * (caseExportArchive.ts) and the plain ZIP import (caseZipImport.ts), so both formats get one
 * path-safety rule, one conflict rule, one integrity hook and one atomic publish.
 *
 * Entries stream from the archive straight into a private staging directory (caseZipReader.ts),
 * so no step holds the inflated case in memory. Nothing becomes visible as a case until the whole
 * staging directory is renamed into place; any failure removes it.
 */

// Where an import extracts before it is published (#420). Dotted, and a level below the cases, so
// nothing that enumerates the cases root can mistake a half-extracted archive for a case.
export const IMPORT_STAGING_DIRNAME = ".import-staging";
const IMPORT_STAGING_MAX_AGE_MS = 24 * 60 * 60 * 1000;
// The folders every case has, created in staging before any entry lands.
const CASE_SUBDIRS = ["screenshots", "metadata", "state", "reports", "imports"];

export class CaseImportConflictError extends Error {
  constructor(
    public readonly caseId: string,
    message = `case ${caseId} already exists — import under a different case id`,
  ) {
    super(message);
    this.name = "CaseImportConflictError";
  }
}

export interface CaseImportCounts {
  forensicEvents: number;
  findings: number;
  iocs: number;
  captures: number;
  imports: number;
}

// Defense-in-depth against a crafted/corrupted archive writing outside the target case
// directory (zip-slip). The primary defense is that the archive is password-authenticated, but
// this guard means a malicious or corrupted entry path is rejected before ANY file is written.
// The colon check also closes an NTFS alternate-data-stream gap: "shot.jpg:hidden.exe" doesn't
// escape the case directory, but would silently write a hidden stream on Windows without it.
//
// It also fixes the archive to ONE path syntax, forward slashes, and rejects the segment spellings
// Windows silently normalizes. Both exist for the same reason (#426): the duplicate check compares
// raw path strings, but the write loop resolves them with the host platform's rules, and on Windows
// several distinct strings resolve to one file. `state/a` and `state\a`, `EVIDENCE.BIN` and
// `evidence.bin`, `notes` and `notes.` all pass a raw-string comparison and then have the later
// entry silently overwrite the earlier one — evidence loss with no error, from a crafted archive or
// from a legitimate one created on a case-sensitive filesystem. A reserved device name (CON, LPT1,
// NUL — with or without an extension) is worse still: on Windows it does not resolve to a file at
// all. Every case archive this tool writes uses forward slashes and ordinary names, so nothing
// legitimate is refused.
const WINDOWS_RESERVED_SEGMENT = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(\..*)?$/i;

export function isSafeZipEntryPath(path: string): boolean {
  if (!path || isAbsolute(path) || /^[a-zA-Z]:/.test(path) || path.includes(":")) return false;
  if (path.includes("\\")) return false;
  return path.split("/").every(
    (seg) =>
      seg !== "" &&
      seg !== "." &&
      seg !== ".." &&
      !/[.\s]$/.test(seg) && // Windows strips trailing dots and spaces
      !/[\x00-\x1f]/.test(seg) && // control characters are not filenames anywhere
      !WINDOWS_RESERVED_SEGMENT.test(seg),
  );
}

/** One archive entry and the case-relative path it restores to. */
export interface CaseZipFile {
  path: string;
  entry: CaseZipEntry;
}

/** What one staged file turned out to be, for an integrity check. */
export interface StagedDigest {
  path: string;
  bytes: number;
  sha256: string;
}

export interface RestoreCaseZipOptions {
  targetCaseId?: string;
  /** Runs after the path-safety pass and before anything is written. Throws to refuse. */
  preflight?: (sourceCaseId: string) => void;
  /**
   * Integrity check over the staged files. Runs AFTER every path has passed the safety check and
   * every entry is staged, and BEFORE the case is published. Throws to refuse the archive.
   * `sourceCaseId` is the id the archive's own case.json claims.
   */
  verify?: (digests: StagedDigest[], sourceCaseId: string) => void;
  /** Files generated by the importer, written after the archive's own entries (they win). */
  extraFiles?: Array<{ path: string; data: Buffer }>;
  /**
   * Runs once the id is known to be free and the archive valid, right before the publish. It
   * throws to refuse the id (a CaseImportConflictError answers 409), and clears state a deleted
   * case with this id left behind (#1831).
   */
  beforePublish?: (caseId: string) => void | Promise<void>;
  /** Count the staged case's entities. Off when the caller already has counts. */
  countEntities?: boolean;
  /** Cap on the staged case's total size. Tests only; defaults to {@link CASE_ZIP_MAX_TOTAL_BYTES}. */
  maxTotalBytes?: number;
}

export interface RestoreCaseZipResult {
  meta: CaseMeta;
  /** The case id the archive's case.json claimed, before any rename. */
  sourceCaseId: string;
  counts: CaseImportCounts;
}

function invalid(reason: string): Error {
  return new Error(`not a valid case archive: ${reason}`);
}

/**
 * Every entry is written back verbatim (byte-for-byte) unless the target case id differs from the
 * archive's own id, in which case the handful of caseId-bearing files are rewritten to keep the
 * imported case internally consistent (case.json, legacy state/investigation.json, and each
 * captures.jsonl / imports.jsonl record; StateStore normalizes an imported SQLite database on
 * first load).
 */
export async function restoreCaseZip(
  store: CaseStore,
  archive: Buffer,
  files: CaseZipFile[],
  options: RestoreCaseZipOptions = {},
): Promise<RestoreCaseZipResult> {
  const caseJsonFile = files.find((f) => f.path === "case.json");
  if (!caseJsonFile) throw invalid("missing case.json");
  const caseJsonData = readCaseZipEntry(archive, caseJsonFile.entry);
  let originalMeta: CaseMeta;
  try {
    originalMeta = JSON.parse(caseJsonData.toString("utf8")) as CaseMeta;
  } catch {
    throw invalid("corrupt case.json");
  }
  if (typeof originalMeta.caseId !== "string" || !originalMeta.caseId) {
    throw invalid("case.json missing caseId");
  }
  const sourceCaseId = originalMeta.caseId;
  const targetCaseId = (options.targetCaseId ?? sourceCaseId).trim();
  if (!isValidCaseId(targetCaseId)) throw new Error(`invalid target case id "${targetCaseId}"`);
  if (await store.caseExists(targetCaseId)) throw new CaseImportConflictError(targetCaseId);

  // Validation before any write: every path is checked (zip-slip / NTFS ADS / duplicates /
  // aliases) before a single byte is staged.
  const extraFiles = options.extraFiles ?? [];
  assertSafeEntryPaths(
    files.map((f) => f.path),
    extraFiles.map((f) => f.path),
  );
  options.preflight?.(sourceCaseId);

  const budget = new StagingBudget(options.maxTotalBytes ?? CASE_ZIP_MAX_TOTAL_BYTES);
  const staging = await createImportStaging(store, targetCaseId);
  let counts: CaseImportCounts = { forensicEvents: 0, findings: 0, iocs: 0, captures: 0, imports: 0 };
  try {
    for (const sub of CASE_SUBDIRS) await mkdir(join(staging, sub), { recursive: true });
    const digests: StagedDigest[] = [];
    for (const file of files) {
      const target = join(staging, file.path);
      await mkdir(dirname(target), { recursive: true });
      const extracted = await extractCaseZipEntry(archive, file.entry, target);
      budget.add(extracted.bytes);
      digests.push({ path: file.path, ...extracted });
    }
    options.verify?.(digests, sourceCaseId);

    if (targetCaseId !== sourceCaseId) {
      await rewriteCaseIds(staging, new Set(files.map((f) => f.path)), targetCaseId, budget);
    }
    for (const extra of extraFiles) {
      const target = join(staging, extra.path);
      await mkdir(dirname(target), { recursive: true });
      budget.add(extra.data.length);
      await writeFile(target, extra.data);
    }
    if (options.countEntities !== false) counts = await countsFromStaging(staging);
    await options.beforePublish?.(targetCaseId);
    await publish(store, staging, targetCaseId);
  } finally {
    // No-op after a successful rename; on any failure it is what keeps a half-extracted archive
    // from surviving as a stale staging directory. Every file handle is closed by now, so the
    // retries only cover a virus scanner or indexer briefly holding a file on Windows.
    await rm(staging, { recursive: true, force: true, maxRetries: 3 }).catch(() => {
      /* best effort */
    });
  }

  const meta = await store.getCaseMeta(targetCaseId);
  if (!meta) throw new Error("import failed: case.json missing after write");
  return { meta, sourceCaseId, counts };
}

/** The staged case's running size, so a caseId rewrite or an extra file cannot push it past the cap. */
class StagingBudget {
  private used = 0;
  constructor(private readonly max: number) {}
  /** Throw if `bytes` more would not fit, without recording them. */
  assertFits(bytes: number): void {
    if (this.used + bytes > this.max)
      throw invalid(`the imported case would grow past the ${this.max} byte cap`);
  }
  add(bytes: number): void {
    this.assertFits(bytes);
    this.used += bytes;
  }
}

/**
 * Paths are keyed by the destination they resolve to, not the raw string, so an alias cannot slip
 * past and overwrite the file an earlier entry wrote (#426). A file may not share its name with a
 * folder another entry needs. An importer-generated extra file may replace an archive entry of the
 * EXACT same path (a re-exported imported case carries its own metadata/source-manifest.json), but
 * never one that merely aliases it.
 */
function assertSafeEntryPaths(paths: string[], extraPaths: string[]): void {
  const seenPaths = new Map<string, string>();
  const folderKeys = new Set(CASE_SUBDIRS.map(destinationKey));
  for (const path of paths) {
    if (!isSafeZipEntryPath(path)) throw invalid(`unsafe entry path "${path}"`);
    const key = destinationKey(path);
    const earlier = seenPaths.get(key);
    if (earlier === path) throw invalid(`duplicate entry path "${path}"`);
    if (earlier !== undefined) {
      throw invalid(
        `entry path "${path}" resolves to the same file as "${earlier}" on a case-insensitive filesystem`,
      );
    }
    seenPaths.set(key, path);
    const segments = path.split("/");
    for (let i = 1; i < segments.length; i++) folderKeys.add(destinationKey(segments.slice(0, i).join("/")));
  }
  for (const [key, path] of seenPaths) {
    if (folderKeys.has(key)) throw invalid(`entry path "${path}" is also a folder in the archive`);
  }
  for (const path of extraPaths) {
    const earlier = seenPaths.get(destinationKey(path));
    if (earlier !== undefined && earlier !== path) {
      throw invalid(
        `entry path "${earlier}" resolves to the same file as "${path}" on a case-insensitive filesystem`,
      );
    }
  }
}

function rewriteCaseIdInJson(data: Buffer, targetCaseId: string, indent: number | undefined): Buffer {
  const parsed = JSON.parse(data.toString("utf8")) as Record<string, unknown>;
  return Buffer.from(JSON.stringify({ ...parsed, caseId: targetCaseId }, null, indent), "utf8");
}

// Legacy archive paths whose caseId must be rewritten on import, mapped to the indent they're
// written back with. investigation.json stays compact because old archives can be near V8's string
// ceiling. SQLite-backed imports normalize the database's caseId on first StateStore load.
// case.json is small and CaseStore writes it pretty, so it stays pretty.
const CASE_ID_JSON_PATHS = new Map<string, number | undefined>([
  ["case.json", 2],
  ["state/investigation.json", undefined],
]);
const CASE_ID_JSONL_PATHS = new Set(["metadata/captures.jsonl", "metadata/imports.jsonl"]);

async function rewriteCaseIds(
  staging: string,
  present: Set<string>,
  targetCaseId: string,
  budget: StagingBudget,
): Promise<void> {
  for (const [path, indent] of CASE_ID_JSON_PATHS) {
    if (!present.has(path)) continue;
    const target = join(staging, path);
    const original = await readFile(target);
    let rewritten: Buffer;
    try {
      rewritten = rewriteCaseIdInJson(original, targetCaseId, indent);
    } catch {
      throw invalid(`corrupt ${path}`);
    }
    budget.add(rewritten.length - original.length);
    await writeFile(target, rewritten);
  }
  for (const path of CASE_ID_JSONL_PATHS) {
    if (present.has(path)) await rewriteCaseIdInJsonl(join(staging, path), path, targetCaseId, budget);
  }
}

/**
 * Rewrite each JSONL record's caseId one line at a time into a sibling file, then replace the
 * original. Growth is measured in bytes actually written against the original file size — never
 * from decoded line lengths, which differ from the raw bytes when the input is not valid UTF-8.
 * Every handle that opened is closed before the rename or any error leaves, which Windows needs.
 */
async function rewriteCaseIdInJsonl(
  target: string,
  path: string,
  targetCaseId: string,
  budget: StagingBudget,
): Promise<void> {
  // A random name no archive entry can have claimed in advance.
  const temp = `${target}.${randomUUID()}.rewrite`;
  const input = await open(target, "r");
  let written = 0;
  try {
    const originalSize = (await input.stat()).size;
    const output = await open(temp, "wx");
    try {
      for await (const line of input.readLines({ autoClose: false })) {
        if (line.trim().length === 0) continue;
        let rewritten: Buffer;
        try {
          const record = JSON.parse(line) as Record<string, unknown>;
          rewritten = Buffer.from(JSON.stringify({ ...record, caseId: targetCaseId }) + "\n", "utf8");
        } catch {
          throw invalid(`corrupt ${path}`);
        }
        written += rewritten.length;
        budget.assertFits(written - originalSize);
        await writeAll(output, rewritten);
      }
    } finally {
      await output.close();
    }
    budget.add(written - originalSize);
  } finally {
    await input.close();
  }
  await renamePath(temp, target);
}

async function countLines(file: string): Promise<number> {
  const input = await open(file, "r").catch(() => null);
  if (!input) return 0;
  let lines = 0;
  try {
    for await (const line of input.readLines({ autoClose: false })) if (line.trim().length > 0) lines++;
  } finally {
    await input.close();
  }
  return lines;
}

async function countsFromStaging(staging: string): Promise<CaseImportCounts> {
  let forensicEvents = 0;
  let findings = 0;
  let iocs = 0;
  // Counts are display only. A legacy investigation.json past the control-file size is not parsed a
  // second time just to count it: the route reads the counts from the loaded state instead.
  const invPath = join(staging, "state", "investigation.json");
  const invSize = (await stat(invPath).catch(() => null))?.size ?? 0;
  const inv = invSize > 0 && invSize <= CASE_ZIP_MAX_CONTROL_BYTES ? await readFile(invPath, "utf8") : null;
  if (inv !== null) {
    try {
      const parsed = JSON.parse(inv) as Record<string, unknown>;
      forensicEvents = Array.isArray(parsed.forensicTimeline) ? parsed.forensicTimeline.length : 0;
      findings = Array.isArray(parsed.findings) ? parsed.findings.length : 0;
      iocs = Array.isArray(parsed.iocs) ? parsed.iocs.length : 0;
    } catch {
      // malformed investigation.json — counts default to 0, import still proceeds
    }
  }
  return {
    forensicEvents,
    findings,
    iocs,
    captures: await countLines(join(staging, "metadata", "captures.jsonl")),
    imports: await countLines(join(staging, "metadata", "imports.jsonl")),
  };
}

/**
 * Publish the staging directory with a single rename (#420).
 *
 * The caseExists() check is not a claim on the id — nothing stopped a second import from passing the
 * same check and then interleaving its writes into the same destination. rename() of a directory
 * onto an existing non-empty directory fails on every platform, which makes it the exclusive atomic
 * claim the existence check never was: the first import to finish publishes, and any other aiming
 * at the same id gets a conflict instead of a merge. A case directory only ever becomes visible
 * complete.
 */
async function publish(store: CaseStore, staging: string, targetCaseId: string): Promise<void> {
  try {
    await renamePath(staging, join(store.casesRoot, targetCaseId));
  } catch (err) {
    // Platforms disagree on the errno for "destination directory is in the way" (ENOTEMPTY,
    // EEXIST, EPERM on Windows), so ask the filesystem what actually happened rather than
    // enumerating codes: if the target is a case now, someone else claimed it.
    if (await store.caseExists(targetCaseId)) throw new CaseImportConflictError(targetCaseId);
    throw err;
  }
}

/**
 * A unique, private directory to extract into, on the same filesystem as the destination so the
 * publishing rename is atomic. It lives under a dotted subdirectory of the cases root rather than
 * beside the cases: listCases() only treats a directory holding a readable case.json as a case, and
 * a half-extracted archive holds exactly that.
 *
 * Also sweeps staging directories older than a day. The finally block above removes this run's on
 * every path a process survives; the sweep is for the one it does not (a kill or a power loss
 * mid-extraction), so those cannot accumulate forever. A day is far longer than any import, so it
 * cannot collide with a slow one running concurrently.
 */
async function createImportStaging(store: CaseStore, targetCaseId: string): Promise<string> {
  const stagingRoot = join(store.casesRoot, IMPORT_STAGING_DIRNAME);
  await mkdir(stagingRoot, { recursive: true });
  const cutoff = Date.now() - IMPORT_STAGING_MAX_AGE_MS;
  for (const name of await readdir(stagingRoot).catch(() => [])) {
    const path = join(stagingRoot, name);
    const info = await stat(path).catch(() => null);
    if (info && info.mtimeMs < cutoff)
      await rm(path, { recursive: true, force: true }).catch(() => {
        /* best effort */
      });
  }
  return mkdtemp(join(stagingRoot, `${targetCaseId}-`));
}
