import { readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { join } from "node:path";
import type { CaseStore } from "../storage/caseStore.js";
import { atomicWrite } from "../storage/atomicWrite.js";
import { StateLock } from "./stateLock.js";
import {
  type Hypothesis,
  type HypothesisSeed,
  type NewHypothesis,
  type HypothesisPatch,
  type ReconsiderHypothesesInput,
  type HypothesisHuntSignal,
  hypothesesSchema,
  mergeHypotheses,
  buildAnalystHypothesis,
  applyHypothesisPatch,
  reconsiderHypotheses,
  markExhaustedHypotheses,
  ensureHypothesisStatusHistory,
} from "./hypothesis.js";

// Per-case hypothesis store (issue #140). Persists `state/hypotheses.json` via the atomic-write
// helper (which retries the rename through transient Dropbox/OneDrive/AV locks). Mirrors
// TagsStore / NotebookStore: a thin I/O wrapper around the pure transforms in hypothesis.ts. NOT
// part of InvestigationState, so synthesis never wipes it; it IS in SNAPSHOT_STATE_FILES.

export class HypothesisStore {
  // Per-case async mutex guarding the load->mutate->save critical section of every mutating method.
  // Without it two concurrent writes (e.g. an analyst flipping two hypotheses at once, or a status
  // PATCH landing while synthesis merges seeds) both read the same list and the second save clobbers
  // the first — silently dropping the other hypothesis's change AND its statusHistory entry, while
  // both HTTP calls return 200. That makes the #95 audit trail unreliable, which defeats its purpose.
  //
  // Deliberately a PRIVATE lock instance, not the pipeline's shared StateLock: synthesis calls
  // applyAutoGenerated() from inside a pipeline withStateLock() section, and StateLock is not
  // reentrant — sharing it would deadlock. This lock only ever guards hypotheses.json.
  private readonly lock = new StateLock();

  constructor(private readonly cases: CaseStore) {}

  private path(caseId: string): string {
    return join(this.cases.stateDir(caseId), "hypotheses.json");
  }

  async load(caseId: string): Promise<Hypothesis[]> {
    try {
      const parsed = hypothesesSchema.parse(JSON.parse(await readFile(this.path(caseId), "utf8")));
      // Backfill statusHistory (issue #95) for hypotheses persisted before that field existed.
      return parsed.map(ensureHypothesisStatusHistory);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") return [];
      throw err;
    }
  }

  private async save(caseId: string, hypotheses: Hypothesis[]): Promise<void> {
    await atomicWrite(this.path(caseId), JSON.stringify(hypotheses, null, 2));
  }

  // Create an analyst-authored hypothesis (server-assigned id + timestamps). Throws on empty title.
  async add(caseId: string, input: NewHypothesis): Promise<Hypothesis> {
    if (!String(input.title ?? "").trim()) throw new Error("title is required");
    return this.lock.runExclusive(caseId, async () => {
      const hypothesis = buildAnalystHypothesis(input, randomUUID(), new Date().toISOString());
      await this.save(caseId, [...(await this.load(caseId)), hypothesis]);
      return hypothesis;
    });
  }

  // Apply an analyst patch (marks the hypothesis analystTouched). Returns the updated hypothesis,
  // or null if no hypothesis with that id exists.
  async update(caseId: string, id: string, patch: HypothesisPatch): Promise<Hypothesis | null> {
    return this.lock.runExclusive(caseId, async () => {
      const hypotheses = await this.load(caseId);
      const now = new Date().toISOString();
      let updated: Hypothesis | null = null;
      const next = hypotheses.map((h) => {
        if (h.id !== id) return h;
        updated = applyHypothesisPatch(h, patch, now);
        return updated;
      });
      if (!updated) return null;
      await this.save(caseId, next);
      return updated;
    });
  }

  // Remove one hypothesis by id; returns true if it existed.
  async remove(caseId: string, id: string): Promise<boolean> {
    return this.lock.runExclusive(caseId, async () => {
      const hypotheses = await this.load(caseId);
      const next = hypotheses.filter((h) => h.id !== id);
      if (next.length === hypotheses.length) return false;
      await this.save(caseId, next);
      return true;
    });
  }

  // Merge freshly-sanitized synthesis seeds into the stored hypotheses (refresh pristine, freeze
  // touched, prune vanished — see mergeHypotheses). Persists only when something changed. Returns
  // the merged list + whether it changed. Called from the synthesis post-processing.
  async applyAutoGenerated(
    caseId: string,
    seeds: readonly HypothesisSeed[],
    now: string = new Date().toISOString(),
  ): Promise<{ changed: boolean; hypotheses: Hypothesis[] }> {
    return this.lock.runExclusive(caseId, async () => {
      const existing = await this.load(caseId);
      const { hypotheses, changed } = mergeHypotheses(existing, seeds, now);
      if (changed) await this.save(caseId, hypotheses);
      return { changed, hypotheses };
    });
  }

  // Immediate FP cascade (investigation-guidance #12): flag/neutralize hypotheses whose supporting
  // evidence was just marked false positive (see reconsiderHypotheses). Persists only when something
  // changed. Called synchronously by the FP-mark route so the dashboard reflects it before re-synthesis.
  async reconsiderForFalsePositive(
    caseId: string,
    input: ReconsiderHypothesesInput,
    now: string = new Date().toISOString(),
  ): Promise<{ changed: boolean; hypotheses: Hypothesis[] }> {
    return this.lock.runExclusive(caseId, async () => {
      const existing = await this.load(caseId);
      const { hypotheses, changed } = reconsiderHypotheses(existing, input, now);
      if (changed) await this.save(caseId, hypotheses);
      return { changed, hypotheses };
    });
  }

  // ACH exhaustion (investigation-guidance #14): flag open hypotheses whose linked/technique-matched
  // hunts have come back empty enough times (see markExhaustedHypotheses). Persists only when something
  // changed. Called from synthesis so the negative-knowledge block reflects it.
  async applyExhaustion(
    caseId: string,
    signals: readonly HypothesisHuntSignal[],
    now: string = new Date().toISOString(),
    minMisses?: number,
  ): Promise<{ changed: boolean; hypotheses: Hypothesis[] }> {
    return this.lock.runExclusive(caseId, async () => {
      const existing = await this.load(caseId);
      const { hypotheses, changed } = markExhaustedHypotheses(existing, signals, now, minMisses);
      if (changed) await this.save(caseId, hypotheses);
      return { changed, hypotheses };
    });
  }
}
