/**
 * The column-name allowlist for import shape reports (#1735).
 *
 * A shape report tells the maintainer how a failed import file is laid out without showing any of
 * its evidence. Nothing can tell a header row from a first data row with certainty — a header-less
 * CSV that opens with "Alice,Finance,ProjectFalcon" looks just like a header — so a first-line field
 * is shown only when it is one of the names below. Everything else is printed as `<unlisted>`.
 *
 * Every entry is a generic column name that some forensic or log tool prints. A name that could
 * identify a person, an organization or a host must never be added. Matching ignores case,
 * underscores, hyphens, spaces and dots (see `normalizeColumnName`).
 */

/** Lowercase, and drop `_`, `-`, space and `.` — "Event_ID", "event-id" and "EventID" all match. */
export function normalizeColumnName(name: string): string {
  return name.toLowerCase().replace(/[_\-\s.]/g, "");
}

const WINDOWS_EVENT_LOG = [
  "TimeCreated",
  "SystemTime",
  "System.TimeCreated.SystemTime",
  "EventID",
  "EventId",
  "Id",
  "EventRecordID",
  "RecordId",
  "RecordNumber",
  "Channel",
  "Provider",
  "ProviderName",
  "ProviderGuid",
  "Computer",
  "MachineName",
  "Level",
  "LevelDisplayName",
  "Task",
  "TaskDisplayName",
  "Opcode",
  "OpcodeDisplayName",
  "Keywords",
  "KeywordsDisplayNames",
  "Message",
  "UserId",
  "ProcessId",
  "ThreadId",
  "ActivityID",
  "RelatedActivityID",
  "Version",
  "Qualifiers",
  "Security",
  "EventData",
  "UserData",
  "System",
  "SubjectUserName",
  "SubjectUserSid",
  "SubjectDomainName",
  "SubjectLogonId",
  "TargetUserName",
  "TargetUserSid",
  "TargetDomainName",
  "TargetLogonId",
  "LogonType",
  "LogonId",
  "LogonProcessName",
  "AuthenticationPackageName",
  "WorkstationName",
  "IpAddress",
  "IpPort",
  "ServiceName",
  "ServiceFileName",
  "ServiceType",
  "StartType",
  "AccountName",
  "ObjectName",
  "ObjectType",
  "AccessMask",
  "Status",
  "SubStatus",
  "FailureReason",
  "TimeGenerated",
  "EventTime",
  "EventTimestamp",
  "Description",
  "Category",
];

const SYSMON = [
  "UtcTime",
  "Image",
  "CommandLine",
  "CurrentDirectory",
  "ParentImage",
  "ParentCommandLine",
  "ParentProcessId",
  "ParentProcessGuid",
  "ProcessGuid",
  "IntegrityLevel",
  "Hashes",
  "LogonGuid",
  "TerminalSessionId",
  "User",
  "TargetFilename",
  "CreationUtcTime",
  "PreviousCreationUtcTime",
  "DestinationIp",
  "DestinationPort",
  "DestinationHostname",
  "DestinationIsIpv6",
  "SourceIp",
  "SourcePort",
  "SourceHostname",
  "SourceIsIpv6",
  "Protocol",
  "Initiated",
  "ImageLoaded",
  "Signed",
  "Signature",
  "SignatureStatus",
  "TargetObject",
  "Details",
  "EventType",
  "QueryName",
  "QueryResults",
  "QueryStatus",
  "SourceImage",
  "TargetImage",
  "GrantedAccess",
  "CallTrace",
  "RuleName",
  "OriginalFileName",
  "FileVersion",
  "Company",
  "Product",
  "PipeName",
];

const VELOCIRAPTOR = [
  "_Source",
  "OSPath",
  "FullPath",
  "Name",
  "Size",
  "Mode",
  "Mtime",
  "Atime",
  "Ctime",
  "Btime",
  "IsDir",
  "IsLink",
  "Data",
  "Hash",
  "MD5",
  "SHA1",
  "SHA256",
  "Pid",
  "Ppid",
  "Exe",
  "Cmdline",
  "Username",
  "CreateTime",
  "StartTime",
  "Created",
  "CreationTime",
  "LastWriteTime",
  "KeyLastWriteTimestamp",
  "KeyMTime",
  "Key",
  "ValueName",
  "ValueData",
  "Type",
  "ClientId",
  "FlowId",
  "Fqdn",
  "Hostname",
  "Enabled",
  "Disabled",
  "Command",
  "Action",
  "Trigger",
];

const PLASO = [
  "datetime",
  "timestamp_desc",
  "source",
  "source_long",
  "message",
  "parser",
  "display_name",
  "tag",
  "date",
  "time",
  "timezone",
  "MACB",
  "sourcetype",
  "type",
  "user",
  "host",
  "short",
  "desc",
  "version",
  "filename",
  "inode",
  "notes",
  "format",
  "extra",
  "timestamp",
];

const HAYABUSA_CHAINSAW = [
  "Timestamp",
  "RuleTitle",
  "RuleFile",
  "RuleID",
  "RuleAuthor",
  "EvtxFile",
  "RecordID",
  "Details",
  "ExtraFieldInfo",
  "MitreTactics",
  "MitreTags",
  "OtherTags",
  "Detections",
  "Rule",
  "Detection",
  "Count",
  "RuleLevel",
  "RuleModifiedDate",
  "Status",
];

const EZ_TOOLS = [
  "SourceFile",
  "EntryNumber",
  "SequenceNumber",
  "ParentEntryNumber",
  "ParentSequenceNumber",
  "InUse",
  "ParentPath",
  "FileName",
  "Extension",
  "FileSize",
  "ReferenceCount",
  "ReparseTarget",
  "IsDirectory",
  "HasAds",
  "IsAds",
  "SI<FN",
  "uSecZeros",
  "Copied",
  "SiFlags",
  "NameType",
  "Created0x10",
  "Created0x30",
  "LastModified0x10",
  "LastModified0x30",
  "LastRecordChange0x10",
  "LastRecordChange0x30",
  "LastAccess0x10",
  "LastAccess0x30",
  "UpdateSequenceNumber",
  "LogfileSequenceNumber",
  "SecurityId",
  "ObjectIdFileDroid",
  "LoggedUtilStream",
  "ZoneIdContents",
  "ExecutableName",
  "RunCount",
  "LastRun",
  "PreviousRun0",
  "PreviousRun1",
  "Hash",
  "Volume0Name",
  "Volume0Serial",
  "Volume0Created",
  "Directories",
  "FilesLoaded",
  "SourceCreated",
  "SourceModified",
  "SourceAccessed",
  "TargetCreated",
  "TargetModified",
  "TargetAccessed",
  "Arguments",
  "WorkingDirectory",
  "LocalPath",
  "RelativePath",
  "FileAttributes",
  "HeaderFlags",
  "DriveType",
  "UpdateTimestamp",
  "UpdateReasons",
  "OffsetToData",
  "KeyPath",
  "ValueType",
  "HivePath",
  "LastWriteTimestamp",
  "AppPath",
  "ProgramName",
  "ProgramID",
  "FileKeyLastWriteTimestamp",
  "SHA1",
  "IsOsComponent",
  "FullPath",
  "LastModifiedTimeUTC",
  "LastExecuted",
  "Executed",
  "ControlSet",
  "CacheEntryPosition",
  "Path",
  "Duplicate",
];

const THOR = [
  "Module",
  "Score",
  "Reason",
  "Reasons",
  "Rule",
  "Subscore",
  "Matched",
  "Scanner",
  "File",
  "Owner",
  "Modified",
  "Accessed",
  "Changed",
  "Firstbytes",
  "Log",
];

const SIEM = [
  "@timestamp",
  "_time",
  "event_time",
  "DeviceEventTime",
  "createdAt",
  "created",
  "event.created",
  "ingested",
  "generated_time",
  "received_time",
  "observed_timestamp",
  "@time",
  "src_ip",
  "dst_ip",
  "src_port",
  "dst_port",
  "src",
  "dst",
  "sport",
  "dport",
  "proto",
  "action",
  "severity",
  "rule",
  "alert",
  "user_name",
  "host_name",
  "process_name",
  "process_path",
  "process_id",
  "parent_process",
  "file_name",
  "file_path",
  "file_hash",
  "url",
  "domain",
  "event_id",
  "event_type",
  "event_name",
  "outcome",
  "result",
  "bytes_in",
  "bytes_out",
  "duration",
  "signature_id",
  "direction",
  "log_source",
  "sourcetype",
  "index",
  "app",
  "category",
];

// Time column spellings the importers already look for (veloRowTime TIME_KEYS, memoryFields
// GENERIC_TIME_KEYS, siemImport TIME_KEYS, mobileLeappImport TIME_COLUMNS).
const IMPORTER_TIME_KEYS = [
  "Last Write Time",
  "Last Written",
  "LastWrite",
  "Last Modified",
  "LastModified",
  "Access Time",
  "AccessTime",
  "Time",
  "start time",
  "date/time",
  "created date",
  "end time",
  "EndTime",
];

// Field keys the importers' own pickers choose among (#1736), so an importer's debug summary can
// name the key it used. Code-authored and generic — never a person, org or host name.
const IMPORTER_FIELD_KEYS = [
  "computer_name",
  "agent.hostname",
  "beat.hostname",
  "device.hostname",
  "endpoint.name",
  "src_host",
  "source.host",
  "winlog.computer_name",
  "DeviceName",
  "EventData.UtcTime",
  "timestamp_ms",
  "threat_level",
  "ImageFileName",
  "kMDItemDisplayName",
  "_kMDItemFileName",
  "kMDItemLastUsedDate",
];

/** The raw allowlist, as the tools spell it. Normalized into a set by `importShape.ts`. */
export const KNOWN_COLUMN_NAME_LIST: readonly string[] = [
  ...WINDOWS_EVENT_LOG,
  ...SYSMON,
  ...VELOCIRAPTOR,
  ...PLASO,
  ...HAYABUSA_CHAINSAW,
  ...EZ_TOOLS,
  ...THOR,
  ...SIEM,
  ...IMPORTER_TIME_KEYS,
  ...IMPORTER_FIELD_KEYS,
];
