import { describe, it, expect } from "vitest";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import request from "supertest";
import { CaseStore } from "../../src/storage/caseStore.js";
import { createApp } from "../../src/server.js";
import { StateStore } from "../../src/analysis/stateStore.js";
import { HypothesisStore } from "../../src/analysis/hypothesisStore.js";
import { emptyState, type Finding, type ForensicEvent } from "../../src/analysis/stateTypes.js";

// Immediate FP cascade (investigation-guidance #12): marking a finding false positive must, BEFORE the
// background re-synthesis runs, neutralize the stored conclusions that rested on it — key questions and
// next-steps (flipped/badged stale) and hypotheses (needsReview / pristine→unknown).

function finding(id: string, title: string): Finding {
  return {
    id, severity: "High", title, description: "d", relatedIocs: [], sourceScreenshots: [],
    mitreTechniques: ["T1059"], firstSeen: "2026-05-20T08:00:00Z", lastUpdated: "2026-05-20T08:00:00Z", status: "open",
  };
}
function event(id: string): ForensicEvent {
  return { id, timestamp: "2026-05-20T09:00:00Z", description: "x", severity: "High", mitreTechniques: [], relatedFindingIds: [], sourceScreenshots: [] };
}

async function setup() {
  const store = new CaseStore(await mkdtemp(join(tmpdir(), "dfir-fpcascade-")));
  const stateStore = new StateStore(store);
  const hypStore = new HypothesisStore(store);
  // Pass the stores in so the FP route's cascade (which reads options.stateStore / options.hypothesisStore)
  // and the test seed/read the SAME instances.
  const app = createApp(store, { stateStore, hypothesisStore: hypStore });
  await request(app).post("/cases").send({ caseId: "c1", name: "n", investigator: "i", aiProvider: null });

  const state = emptyState("c1");
  state.forensicTimeline.push(event("e1"));
  state.findings.push(finding("f1", "PS abuse"), finding("f2", "other real finding"));
  state.keyQuestions = [
    { id: "q1", question: "How did they execute code?", status: "answered", answer: "via f1", pointer: "finding f1", relatedFindingIds: ["f1"] },
    { id: "q2", question: "unrelated", status: "answered", answer: "backed by f2", pointer: "", relatedFindingIds: ["f2"] },
  ];
  state.nextSteps = [
    { id: "n1", priority: "high", action: "Confirm the PS abuse in f1", rationale: "", pointer: "", relatedFindingIds: ["f1"] },
    { id: "n2", priority: "medium", action: "unrelated pivot", rationale: "", pointer: "", relatedFindingIds: ["f2"] },
  ];
  await stateStore.save(state);

  await hypStore.applyAutoGenerated("c1", [
    { sourceKey: "synth:aaa", title: "Execution via PowerShell", description: "", expectedOutcome: "",
      status: "supported", relatedTechniques: ["T1059"], relatedEventIds: ["e1"], relatedIocIds: [] },
  ], "2026-05-20T08:30:00Z");

  return { app, stateStore, hypStore };
}

describe("POST /cases/:id/false-positive → immediate cascade (#12)", () => {
  it("neutralizes dependent key questions and next-steps and flags hypotheses, synchronously", async () => {
    const { app, stateStore, hypStore } = await setup();

    // Mark the event that supports the hypothesis FP …
    await request(app).post("/cases/c1/false-positive").send({ kind: "event", ref: "e1", reason: "benign", note: "sanctioned admin" });
    // … and the finding the question/step rest on (findings match by title).
    const res = await request(app).post("/cases/c1/false-positive").send({ kind: "finding", ref: "PS abuse", reason: "benign", note: "sanctioned admin" });
    expect(res.status).toBe(200);

    const state = await stateStore.load("c1");
    const q1 = state.keyQuestions.find((q) => q.id === "q1")!;
    expect(q1.status).toBe("unknown");
    expect(q1.answer).toBe("");
    expect(q1.staleReSynth).toBe(true);
    // The unrelated question (rests on f2, still real) is untouched.
    expect(state.keyQuestions.find((q) => q.id === "q2")!.status).toBe("answered");

    const n1 = state.nextSteps.find((n) => n.id === "n1")!;
    expect(n1.staleReSynth).toBe(true);
    expect(state.nextSteps.find((n) => n.id === "n2")!.staleReSynth).toBeUndefined();

    // The pristine hypothesis whose supporting event was rejected is flipped + flagged.
    const hyps = await hypStore.load("c1");
    expect(hyps[0].needsReview).toBe(true);
    expect(hyps[0].status).toBe("unknown");
  });
});
