import { describe, it, expect } from "vitest";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import request from "supertest";
import { CaseStore } from "../../src/storage/caseStore.js";
import { createApp, buildRuntimePipeline } from "../../src/server.js";
import { StateStore } from "../../src/analysis/stateStore.js";
import { HypothesisStore } from "../../src/analysis/hypothesisStore.js";
import { hypothesisAutoKey } from "../../src/analysis/hypothesis.js";
import { MockProvider } from "../../src/providers/provider.js";
import { emptyState } from "../../src/analysis/stateTypes.js";

// Build an app with a case that has one forensic event and, unless `seedHypothesis` is false, one OPEN
// hypothesis. The MockProvider is constructed AFTER the hypothesis so its canned review can reference the
// real (generated) hypothesis id — plus a ghost id and an out-of-enum status to exercise sanitization.
async function makeApp(opts: { ai?: boolean; seedHypothesis?: boolean } = {}) {
  const ai = opts.ai ?? true;
  const seedHypothesis = opts.seedHypothesis ?? true;
  const root = await mkdtemp(join(tmpdir(), "dfir-hyprev-"));
  const store = new CaseStore(root);
  const stateStore = new StateStore(store);
  const hypothesisStore = new HypothesisStore(store);
  await store.createCase({ caseId: "c1", name: "n", investigator: "i", aiProvider: ai ? "mock" : null });

  const s = emptyState("c1");
  s.forensicTimeline.push({
    id: "ev1", timestamp: "2026-06-01T10:00:00Z", description: "inbox rule created",
    severity: "High", mitreTechniques: ["T1114"], relatedFindingIds: [], sourceScreenshots: [], asset: "WS01",
  });
  await stateStore.save(s);

  // Seed a PRISTINE synthesis hypothesis (analystTouched: false, id = its deterministic sourceKey) — the
  // strongest advisory-only test: the review must not flip its status OR mark it touched.
  let hypId = "";
  if (seedHypothesis) {
    const title = "Initial access was phishing";
    hypId = hypothesisAutoKey(title);
    await hypothesisStore.applyAutoGenerated("c1", [{
      sourceKey: hypId, title, description: "", expectedOutcome: "", status: "open",
      relatedTechniques: [], relatedEventIds: [], relatedIocIds: [], contradictingEventIds: [], discriminator: "",
    }]);
  }

  const canned = JSON.stringify({
    reviews: [
      {
        hypothesisId: hypId || "none",
        title: "echoed (drifted) title that must be ignored",
        supportingEvidence: ["an inbox rule was created (ev1)", "an inbox rule was created (ev1)"],
        refutingEvidence: ["no phishing email found in the mail logs"],
        recommendedStatus: "PROBABLY_TRUE",           // out-of-enum → coerced to "unknown"
        rationale: "Rule creation is consistent, but the originating email is absent.",
        relatedEventIds: ["ev1", "ghostEvent"],        // ghost dropped
      },
      { hypothesisId: "ghost", recommendedStatus: "refuted" }, // invented target → dropped
    ],
  });
  const provider = ai ? new MockProvider("mock", canned) : undefined;
  const pipeline = buildRuntimePipeline({
    provider, synthesisProvider: provider, stateStore, store, hypothesisStore,
    imageLoader: async () => ({ base64: "AAAA", mimeType: "image/webp" }),
  });
  const app = createApp(store, { pipeline, stateStore, hypothesisStore, aiConfigured: ai });
  return { app, hypId };
}

describe("POST /cases/:id/hypothesis-review (#71)", () => {
  it("reviews open hypotheses and sanitizes the model response (advisory, real refs only)", async () => {
    const { app, hypId } = await makeApp();
    const res = await request(app).post("/cases/c1/hypothesis-review").send({});
    expect(res.status).toBe(200);
    expect(res.body.reviews).toHaveLength(1);           // ghost review dropped
    const r = res.body.reviews[0];
    expect(r.hypothesisId).toBe(hypId);
    expect(r.title).toBe("Initial access was phishing"); // KNOWN title, not the echoed one
    expect(r.supportingEvidence).toEqual(["an inbox rule was created (ev1)"]); // deduped
    expect(r.refutingEvidence).toEqual(["no phishing email found in the mail logs"]);
    expect(r.recommendedStatus).toBe("unknown");         // coerced from out-of-enum
    expect(r.relatedEventIds).toEqual(["ev1"]);          // ghostEvent dropped
  });

  it("does NOT mutate the hypothesis (recommendation is advisory)", async () => {
    const { app, hypId } = await makeApp();
    await request(app).post("/cases/c1/hypothesis-review").send({});
    const list = (await request(app).get("/cases/c1/hypotheses")).body;
    const h = list.find((x: { id: string }) => x.id === hypId);
    expect(h.status).toBe("open");          // unchanged
    expect(h.analystTouched).toBe(false);   // review never touches it
  });

  it("returns { reviews: [] } with no open hypotheses", async () => {
    const { app } = await makeApp({ seedHypothesis: false });
    const res = await request(app).post("/cases/c1/hypothesis-review").send({});
    expect(res.status).toBe(200);
    expect(res.body.reviews).toEqual([]);
  });

  it("returns 501 when AI is not configured", async () => {
    const { app } = await makeApp({ ai: false });
    const res = await request(app).post("/cases/c1/hypothesis-review").send({});
    expect(res.status).toBe(501);
  });
});
